import {
  City,
  Review,
  Meetup,
  TrendingCity,
  LiveDashboard,
  PricingPlan,
  StatCard,
  FilterOption,
} from "@/types";

// 15개 한국 도시 데이터
export const CITIES: City[] = [
  {
    id: "1",
    name: "강릉",
    slug: "gangneung",
    region: "강원도",
    thumbnail: "/images/cities/gangneung.jpg",
    description: "바다와 카페, 조용한 환경이 완벽한 조화",
    badge: "popular",
    monthlyCost: 1800000,
    rentStudio: 450000,
    deposit: 5000000,
    internetSpeed: 1000,
    cafeCount: 320,
    coworkingCount: 5,
    avgTemperature: 12,
    currentTemperature: 5,
    airQuality: 45,
    rating: 4.5,
    nomadScore: 4.7,
    reviewCount: 120,
    likeCount: 85,
    nomadsNow: 23,
  },
  {
    id: "2",
    name: "제주",
    slug: "jeju",
    region: "제주특별자치도",
    thumbnail: "/images/cities/jeju.jpg",
    description: "따뜻한 날씨와 활발한 커뮤니티",
    badge: "popular",
    monthlyCost: 2200000,
    rentStudio: 600000,
    deposit: 10000000,
    internetSpeed: 500,
    cafeCount: 520,
    coworkingCount: 8,
    avgTemperature: 16,
    currentTemperature: 12,
    airQuality: 60,
    rating: 4.7,
    nomadScore: 4.8,
    reviewCount: 230,
    likeCount: 92,
    nomadsNow: 67,
  },
  {
    id: "3",
    name: "부산",
    slug: "busan",
    region: "부산광역시",
    thumbnail: "/images/cities/busan.jpg",
    description: "도시와 바다의 균형, 네트워킹 기회",
    badge: "popular",
    monthlyCost: 2000000,
    rentStudio: 550000,
    deposit: 8000000,
    internetSpeed: 1000,
    cafeCount: 1050,
    coworkingCount: 12,
    avgTemperature: 15,
    currentTemperature: 8,
    airQuality: 55,
    rating: 4.3,
    nomadScore: 4.4,
    reviewCount: 180,
    likeCount: 78,
    nomadsNow: 45,
  },
  {
    id: "4",
    name: "서울",
    slug: "seoul",
    region: "서울특별시",
    thumbnail: "/images/cities/seoul.jpg",
    description: "모든 것의 중심, 최고의 인프라",
    badge: "popular",
    monthlyCost: 2800000,
    rentStudio: 800000,
    deposit: 10000000,
    internetSpeed: 1000,
    cafeCount: 2200,
    coworkingCount: 25,
    avgTemperature: 12,
    currentTemperature: 3,
    airQuality: 70,
    rating: 4.2,
    nomadScore: 4.0,
    reviewCount: 350,
    likeCount: 75,
    nomadsNow: 120,
  },
  {
    id: "5",
    name: "전주",
    slug: "jeonju",
    region: "전라북도",
    thumbnail: "/images/cities/jeonju.jpg",
    description: "가성비 최고, 한옥마을의 매력",
    badge: "rising",
    monthlyCost: 1500000,
    rentStudio: 350000,
    deposit: 3000000,
    internetSpeed: 500,
    cafeCount: 180,
    coworkingCount: 3,
    avgTemperature: 13,
    currentTemperature: 4,
    airQuality: 50,
    rating: 4.4,
    nomadScore: 4.5,
    reviewCount: 85,
    likeCount: 82,
    nomadsNow: 18,
  },
  {
    id: "6",
    name: "포항",
    slug: "pohang",
    region: "경상북도",
    thumbnail: "/images/cities/pohang.jpg",
    description: "조용한 환경, 저렴한 생활비",
    badge: "rising",
    monthlyCost: 1600000,
    rentStudio: 380000,
    deposit: 4000000,
    internetSpeed: 500,
    cafeCount: 120,
    coworkingCount: 2,
    avgTemperature: 14,
    currentTemperature: 5,
    airQuality: 52,
    rating: 4.2,
    nomadScore: 4.3,
    reviewCount: 65,
    likeCount: 70,
    nomadsNow: 11,
  },
  {
    id: "7",
    name: "대전",
    slug: "daejeon",
    region: "대전광역시",
    thumbnail: "/images/cities/daejeon.jpg",
    description: "과학 기술의 중심, 좋은 인프라",
    monthlyCost: 1700000,
    rentStudio: 420000,
    deposit: 5000000,
    internetSpeed: 1000,
    cafeCount: 250,
    coworkingCount: 6,
    avgTemperature: 13,
    currentTemperature: 4,
    airQuality: 58,
    rating: 4.1,
    nomadScore: 4.2,
    reviewCount: 70,
    likeCount: 68,
    nomadsNow: 8,
  },
  {
    id: "8",
    name: "광주",
    slug: "gwangju",
    region: "광주광역시",
    thumbnail: "/images/cities/gwangju.jpg",
    description: "예술과 미식의 도시",
    monthlyCost: 1650000,
    rentStudio: 400000,
    deposit: 4500000,
    internetSpeed: 500,
    cafeCount: 200,
    coworkingCount: 4,
    avgTemperature: 14,
    currentTemperature: 5,
    airQuality: 55,
    rating: 4.0,
    nomadScore: 4.1,
    reviewCount: 55,
    likeCount: 65,
    nomadsNow: 7,
  },
  {
    id: "9",
    name: "수원",
    slug: "suwon",
    region: "경기도",
    thumbnail: "/images/cities/suwon.jpg",
    description: "서울 근접, 좋은 접근성",
    monthlyCost: 1900000,
    rentStudio: 480000,
    deposit: 6000000,
    internetSpeed: 1000,
    cafeCount: 380,
    coworkingCount: 7,
    avgTemperature: 12,
    currentTemperature: 3,
    airQuality: 62,
    rating: 4.2,
    nomadScore: 4.3,
    reviewCount: 95,
    likeCount: 72,
    nomadsNow: 15,
  },
  {
    id: "10",
    name: "속초",
    slug: "sokcho",
    region: "강원도",
    thumbnail: "/images/cities/sokcho.jpg",
    description: "해산물과 자연의 만남",
    badge: "new",
    monthlyCost: 1700000,
    rentStudio: 420000,
    deposit: 5000000,
    internetSpeed: 500,
    cafeCount: 150,
    coworkingCount: 2,
    avgTemperature: 12,
    currentTemperature: 4,
    airQuality: 48,
    rating: 4.3,
    nomadScore: 4.4,
    reviewCount: 45,
    likeCount: 68,
    nomadsNow: 9,
  },
  {
    id: "11",
    name: "통영",
    slug: "tongyeong",
    region: "경상남도",
    thumbnail: "/images/cities/tongyeong.jpg",
    description: "아름다운 해안가, 조용한 분위기",
    badge: "rising",
    monthlyCost: 1550000,
    rentStudio: 380000,
    deposit: 4000000,
    internetSpeed: 500,
    cafeCount: 90,
    coworkingCount: 2,
    avgTemperature: 14,
    currentTemperature: 6,
    airQuality: 50,
    rating: 4.4,
    nomadScore: 4.5,
    reviewCount: 38,
    likeCount: 74,
    nomadsNow: 7,
  },
  {
    id: "12",
    name: "여수",
    slug: "yeosu",
    region: "전라남도",
    thumbnail: "/images/cities/yeosu.jpg",
    description: "섬과 바다의 아름다움",
    monthlyCost: 1500000,
    rentStudio: 350000,
    deposit: 3500000,
    internetSpeed: 500,
    cafeCount: 110,
    coworkingCount: 2,
    avgTemperature: 14,
    currentTemperature: 6,
    airQuality: 52,
    rating: 4.3,
    nomadScore: 4.4,
    reviewCount: 42,
    likeCount: 70,
    nomadsNow: 8,
  },
  {
    id: "13",
    name: "진주",
    slug: "jinju",
    region: "경상남도",
    thumbnail: "/images/cities/jinju.jpg",
    description: "전통과 현대의 조화",
    monthlyCost: 1450000,
    rentStudio: 340000,
    deposit: 3500000,
    internetSpeed: 500,
    cafeCount: 85,
    coworkingCount: 2,
    avgTemperature: 13,
    currentTemperature: 4,
    airQuality: 51,
    rating: 4.2,
    nomadScore: 4.3,
    reviewCount: 35,
    likeCount: 66,
    nomadsNow: 6,
  },
  {
    id: "14",
    name: "춘천",
    slug: "chuncheon",
    region: "강원도",
    thumbnail: "/images/cities/chuncheon.jpg",
    description: "호수와 산의 풍경, 맛집 도시",
    monthlyCost: 1600000,
    rentStudio: 400000,
    deposit: 4500000,
    internetSpeed: 500,
    cafeCount: 140,
    coworkingCount: 3,
    avgTemperature: 11,
    currentTemperature: 2,
    airQuality: 47,
    rating: 4.3,
    nomadScore: 4.4,
    reviewCount: 48,
    likeCount: 69,
    nomadsNow: 9,
  },
  {
    id: "15",
    name: "경주",
    slug: "gyeongju",
    region: "경상북도",
    thumbnail: "/images/cities/gyeongju.jpg",
    description: "역사와 문화의 도시",
    badge: "new",
    monthlyCost: 1500000,
    rentStudio: 360000,
    deposit: 4000000,
    internetSpeed: 500,
    cafeCount: 95,
    coworkingCount: 2,
    avgTemperature: 13,
    currentTemperature: 4,
    airQuality: 53,
    rating: 4.1,
    nomadScore: 4.2,
    reviewCount: 32,
    likeCount: 64,
    nomadsNow: 5,
  },
];

// 리뷰 데이터
export const REVIEWS: Review[] = [
  {
    id: "1",
    cityId: "1",
    city: "강릉",
    user: {
      name: "김노마드",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kim",
    },
    rating: 5.0,
    content:
      "강릉은 바다와 카페, 조용한 환경이 완벽한 조화를 이룹니다. 서울까지 2시간이면 가능해서 가끔 미팅도 다녀올 수 있어요!",
    duration: "6개월 거주",
    helpfulCount: 45,
    commentCount: 8,
    timeAgo: "2시간 전",
  },
  {
    id: "2",
    cityId: "2",
    city: "제주",
    user: {
      name: "박프리랜서",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Park",
    },
    rating: 5.0,
    content:
      "제주는 날씨도 좋고 커뮤니티도 활발해요. 매주 밋업이 있어서 외롭지 않아요. 생활비는 조금 비싸지만 그만한 가치가 있어요!",
    duration: "3개월 거주",
    helpfulCount: 32,
    commentCount: 5,
    timeAgo: "5시간 전",
  },
  {
    id: "3",
    cityId: "3",
    city: "부산",
    user: {
      name: "이개발자",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lee",
    },
    rating: 4.5,
    content:
      "해운대 카페거리에서 작업하기 정말 좋아요. 네트워킹 기회도 많고, 도시의 편리함과 바다의 여유를 동시에 즐길 수 있어요.",
    duration: "4개월 거주",
    helpfulCount: 28,
    commentCount: 4,
    timeAgo: "1일 전",
  },
  {
    id: "4",
    cityId: "5",
    city: "전주",
    user: {
      name: "최디자이너",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Choi",
    },
    rating: 4.8,
    content:
      "한옥마을에서 일하는 느낌이 정말 특별해요. 생활비도 저렴하고 음식이 맛있어서 장기 거주하기에 최고입니다.",
    duration: "2개월 거주",
    helpfulCount: 22,
    commentCount: 3,
    timeAgo: "2일 전",
  },
];

// 밋업 데이터
export const MEETUPS: Meetup[] = [
  {
    id: "1",
    cityId: "1",
    city: "강릉",
    title: "강릉 카페 모각코",
    icon: "☕",
    description: "함께 카페에서 각자 할 일 하면서 친목도 만들어요",
    type: "cafe",
    date: "1월 20일 (월)",
    time: "14:00",
    location: "스타벅스 강릉교동점",
    maxAttendees: 10,
    currentAttendees: 8,
    status: "confirmed",
  },
  {
    id: "2",
    cityId: "2",
    city: "제주",
    title: "제주 노마드 저녁 모임",
    icon: "🍺",
    description: "일주일 동안의 이야기를 나누며 맛있는 저녁을 같이 먹어요",
    type: "dinner",
    date: "1월 22일 (수)",
    time: "19:00",
    location: "제주 애월 카페거리",
    maxAttendees: 15,
    currentAttendees: 12,
    status: "confirmed",
  },
  {
    id: "3",
    cityId: "3",
    city: "부산",
    title: "부산 해운대 러닝",
    icon: "🏃",
    description: "아침 일찍 해운대 해변을 함께 뛰어요",
    type: "sports",
    date: "1월 25일 (토)",
    time: "07:00",
    location: "해운대해수욕장",
    maxAttendees: 10,
    currentAttendees: 6,
    status: "confirmed",
  },
];

// 트렌딩 도시 데이터
export const TRENDING_CITIES: TrendingCity[] = [
  {
    id: "1",
    name: "강릉",
    popularity: 100,
    growthRate: 15,
    trend: "up",
    insights: ["겨울 바다가 매력적", "카페 투어 인기"],
  },
  {
    id: "2",
    name: "제주",
    popularity: 85,
    growthRate: 8,
    trend: "up",
    insights: ["따뜻한 날씨", "워케이션 성수기"],
  },
  {
    id: "3",
    name: "부산",
    popularity: 75,
    growthRate: 5,
    trend: "up",
    insights: ["도시+바다 균형", "네트워킹 기회"],
  },
  {
    id: "4",
    name: "전주",
    popularity: 60,
    growthRate: 3,
    trend: "up",
    insights: ["가성비 최고", "한옥마을 매력"],
  },
  {
    id: "5",
    name: "포항",
    popularity: 50,
    growthRate: 2,
    trend: "up",
    insights: ["조용한 환경", "저렴한 생활비"],
  },
];

// 실시간 대시보드 데이터
export const LIVE_DASHBOARD: LiveDashboard = {
  totalNomads: 234,
  cityDistribution: [
    { cityId: "4", cityName: "서울", count: 52 },
    { cityId: "3", cityName: "부산", count: 28 },
    { cityId: "2", cityName: "제주", count: 19 },
    { cityId: "1", cityName: "강릉", count: 15 },
    { cityId: "5", cityName: "전주", count: 11 },
    { cityId: "6", cityName: "포항", count: 8 },
    { cityId: "7", cityName: "대전", count: 7 },
    { cityId: "8", cityName: "광주", count: 6 },
    { cityId: "기타", cityName: "기타", count: 88 },
  ],
};

// 프리미엄 플랜 데이터
export const PRICING_PLANS: PricingPlan[] = [
  {
    tier: "free",
    name: "FREE",
    price: 0,
    features: [
      "기본 도시 정보",
      "5개 도시 비교",
      "밋업 참여",
      "커뮤니티 접근",
    ],
  },
  {
    tier: "premium",
    name: "PREMIUM",
    price: 9900,
    featured: true,
    features: [
      "모든 FREE 혜택",
      "모든 도시 상세 데이터",
      "무제한 도시 비교",
      "AI 맞춤 추천",
      "생활비 시뮬레이터",
      "밋업 호스팅",
      "프리미엄 배지",
    ],
  },
  {
    tier: "pro",
    name: "PRO",
    price: 19900,
    features: [
      "모든 PREMIUM 혜택",
      "1:1 컨설팅",
      "프리미엄 밋업",
      "광고 제거",
      "조기 접근",
      "제휴 할인",
      "우선 지원",
    ],
  },
];

// 통계 카드 데이터
export const STATS: StatCard[] = [
  { icon: "📊", value: 1234, label: "활성회원" },
  { icon: "💬", value: 5678, label: "리뷰" },
  { icon: "🥥", value: 308, label: "밋업/년" },
  { icon: "⭐", value: 4.6, label: "평균평점" },
];

// 빠른 필터 옵션
export const QUICK_FILTERS: FilterOption[] = [
  { icon: "💰", label: "저렴함", filter: "cost<1800000" },
  { icon: "📡", label: "빠른 인터넷", filter: "internet>=1000" },
  { icon: "☕", label: "카페 많음", filter: "cafes>=300" },
  { icon: "🌤️", label: "날씨 좋음", filter: "weather_score>=4" },
  { icon: "🚄", label: "서울 근처", filter: "seoul_distance<=3" },
  { icon: "🌊", label: "바다 근처", filter: "near_sea=true" },
];

// 네비게이션 메뉴
export const NAV_MENU = [
  { name: "홈", href: "/" },
  { name: "도시", href: "/cities" },
  { name: "밋업", href: "/meetups" },
  { name: "커뮤니티", href: "/community" },
];

// 푸터 링크
export const FOOTER_LINKS = {
  service: [
    { name: "도시 찾기", href: "/cities" },
    { name: "리뷰 작성", href: "/reviews" },
    { name: "AI 추천", href: "/ai-recommend" },
    { name: "비교하기", href: "/compare" },
    { name: "멤버십", href: "/pricing" },
  ],
  community: [
    { name: "밋업", href: "/meetups" },
    { name: "Q&A 게시판", href: "/forum" },
    { name: "채팅", href: "/chat" },
    { name: "블로그", href: "/blog" },
    { name: "이벤트", href: "/events" },
  ],
  support: [
    { name: "FAQ", href: "/faq" },
    { name: "문의하기", href: "/contact" },
    { name: "가이드", href: "/guide" },
    { name: "이용약관", href: "/terms" },
    { name: "개인정보처리방침", href: "/privacy" },
  ],
  social: [
    { name: "Facebook", href: "https://facebook.com", icon: "📘" },
    { name: "Instagram", href: "https://instagram.com", icon: "📷" },
    { name: "Twitter", href: "https://twitter.com", icon: "🐦" },
    { name: "YouTube", href: "https://youtube.com", icon: "📺" },
    { name: "카카오톡", href: "https://kakao.com", icon: "💬" },
  ],
};
